### PR TITLE
Feature collapse all items

### PR DESCRIPTION
**Pull request by AlencarGabriel**
Hello @oleg-shilo , my name is Gabriel and I am from Brazil.

I wrote an article on my blog (https://gabrielalencar.dev/2019/12/01/Outline-Advpl-VsCode) where I present its extension as a solution to a problem in an ERP programming language that I work with. Since we don't have a VsCode-ready language server yet supporting this language, its extension was essential for us with this Outline-like feature.

After I introduced your extension, many friends downloaded and liked it. But me and many of them wanted the feature requested in issue #17.

As I am also a developer of extensions for VsCode and would really like this feature, I decided to implement and send it to you as soon as possible.

**I apologize for the grammar, as I am not fluent in English. So feel free to contact us.**

---

- Implemented native VsCode feature to collapse items;
- Added setting that allows the user to choose whether items will be expanded or collapsed.

### CODE REVIEW

**Comment by oleg-shilo** [comment]
Excellent. Thank you.

**Comment by oleg-shilo** [comment]
I have some problems here and hope you can assist me.

The API changes you are using (`createTreeView`) are causing the failure to package and even have error free load in VSCode:

image


However to my surprise if I ignore the error and debug it works just fine...

Any idea?

**Comment by AlencarGabriel** [comment]
Hi,

Did you update the NPM packages before compiling?

One of my changes for this API to work was to update the VsCode package version. If it still doesn't work, I recommend deleting package-lock.json, the node_modules folder and running NPM INSTALL again.

**Comment by oleg-shilo** [comment]
Yep, this is what I did. Cleared lock, modules and run npm install. 
Tried everything including npm cache clear.
On top of it I even cloned a fresh copy of repo. No joy. Will see if I can use a different environment to build the package.

**Comment by AlencarGabriel** [comment]
running "Npm run compile" runs without errors?

Em qui, 5 de dez de 2019 19:25, Oleg Shilo <notifications@github.com>
escreveu:

**Comment by oleg-shilo** [comment]
Yep, this is what I did. Cleared lock, modules and run npm install. 
Tried everything including npm cache clear.
On top of it I even cloned a fresh copy of repo. No joy. Will see if I can use a different environment to build the package.

**Comment by AlencarGabriel** [comment]
image

This is the result of my, runs smoothly.

**Comment by oleg-shilo** [comment]
Found it! Had to create a dummy new extension to detect the difference in `package.json` :)

The bit that was missing is the engine version upgrade:

image

It makes sense. The old v1.13.0 does not have that `createTreeView` API. 

Sorry, have no idea why it does not cause any problem in your case. :)
It still might if you try to create the package (`vcse package`), which is the most strict from compiling point of view.

Anyway, all done and already published.

Thank you for your contributioin.

**Comment by AlencarGabriel** [comment]
Maravilha, fico feliz que tenha encontrado o problema e era algo simples.

Por curiosidade, executei o `vsce package` no meu clone, e tambem executou sem problemas, realmente é algo inexplicavel comigo funcionar.

Mas enfim, fico feliz em ter ajudado, e espero contribuir mais em outras oportunidades.

**Comment by AlencarGabriel** [comment]
Wonderful, I'm glad you found the problem and it was simple.

Out of curiosity, I ran vsce package on my clone, and it also ran smoothly, it really is inexplicable for me to work.

But anyway, I'm glad to have helped, and I hope to contribute more in other opportunities.

**Comment by oleg-shilo** [comment]
To be honest, this one of the awkward things that I experience with VSCode extension authoring. 
Since all my extensions are relatively stable I only update them occasionally. But every time I do I experience a few hiccups. :)

Thus even with the faulty `package.json` I could run/debug the extension but not package. Even though I should not be able to do anything at all.

Does not matter. All good now.
Gracias

**Comment by AlencarGabriel** [comment]
I've seen this kind of weird behavior happen in other extensions as well.
They really are difficult things to understand kkkk.

Good thing everything is all right now!


Em sex., 6 de dez. de 2019 às 09:47, Oleg Shilo <notifications@github.com>
escreveu:

**Pull request merged**
