### PR TITLE
Add an option to put the code map back into the explorer

### PR DESCRIPTION
**Pull request by greatpate**
I liked it when the code map was available in the explorer menu, so I added an option for people to be able to move it back there if they want to. The default will be how it is currently (code map explorer)

### CODE REVIEW

**Comment by oleg-shilo** [comment]
Excellent contribution. Will make it into the very next release.

**Comment by oleg-shilo** [comment]
Hey Daniel, can you please have a look the code chage. I just released it and it it seems like it at has unexpected side effect #28.

BTW, it's pleasure to have fellow Australians contributing :)

**Comment by AlencarGabriel** [comment]
any news?

**Comment by oleg-shilo** [comment]
As you can see Daniel did has not answered.

I do not have capacity to handle this issue right now so if Daniel does not respond in, let's say next 3 days I suggest you downgrade the extension to the prev working version. 

And if my capacity will nor improve in a week I will rollback the published version.

**Comment by AlencarGabriel** [comment]
Ok I understand.

I'll see if I can look at something this week to help, I've already used this View API a lot in another extension that I contribute.

**Comment by oleg-shilo** [comment]
Fantastic. Txs

**Pull request merged**
